Provide support for top_const_ref nodes
stripe/yard-sorbet pull request #2
Opened 2020-11-13 21:10 UTC by KaanOzkan

Came across these nodes when using sigs that contain ::Klass syntax to represent user defined types.

2020-11-16 18:11 UTC, dduugg requested changes
Thanks! Could I trouble you to add tests for each node type?

2020-11-16 18:11 UTC, dduugg commented on lib/yard-sorbet/sig_to_yard.rb
> +    when :const
let's add this to `when :const_path_ref` above

2020-11-16 19:09 UTC, KaanOzkan commented
> Thanks! Could I trouble you to add tests for each node type?

Sure, were you thinking of extending `sig_handler.rb.txt` and `sig_handler_spec.rb` or create a new `sig_to_yard_spec` and `sig_to_yard.rb.txt` and make it more of a unit test for the `convert` method @dduugg ?

2020-11-16 20:12 UTC, dduugg commented
@KaanOzkan I'd recommend just extending the `sig_handler*` files. (I'm open to unit tests as well, if you feel inspired.)

2020-11-17 15:57 UTC, KaanOzkan commented on lib/yard-sorbet/sig_to_yard.rb
>      when :hash, :list
I wasn't sure what a `list` node is and did not test it.

2020-11-19 01:00 UTC, dduugg commented
Looks good! However, I just realized this is under the `stripe` account, not `dduugg`, the account that publishes the gem. Could I trouble you to re-open your PRs under https://github.com/dduugg/yard-sorbet ?

In the meantime, I'll see if I can get someone at Stripe to hide this repo, add a disclaimer, or take ownership of the gem.

2020-11-19 15:47 UTC, closed without merging